### ISSUE TITLE
SBS 라디오가 나오지 않는 것 같습니다.

### ISSUE THREAD

**Issue by pilos011** [miumida/korea_radio#2]
안녕하세요?

너무 잘 사용하고 있습니다. 이번에 SBS 라디오가 되어서 설치를 해보았는데 MBC 3채널을 잘 나오는데 SBS3 채널은
재생되지 않아서 문의 드립니다.

수고하심에 감사드립니다!

**Comment by miumida** [comment]
스트리밍 문제로 되지 않을 수도 있습니다.
스트리밍 문제나 크롬캐스트 문제로 인해서 재생되지 않는 경우는 확인 불가합니다.

제 기준으로 현재 SBS 재생중인데 큰문제는 없어보이네요.
